name: BasedPyright checks
on: [push, pull_request]

jobs:
  basedpyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python

      - name: Run BasedPyright
        run: pdm run basedpyright
